version: "1.0"

# ⚠️ IMPORTANT: After editing this file, run `uvx ritual-pr-infra update-workflows`
# to regenerate the GitHub Actions workflows with your changes.
# 
# This config is used at generation time, not at runtime. The workflows are
# generated once and run independently, so changes here require regeneration.

manus:
  enabled: true
  prompts:
    - shared/engineering.md
    - shared/fsm-verification.md
  trigger:
    "on": [opened, synchronize]
    labels: []  # Optional: only run if PR has these labels

claude:
  enabled: true
  prompts:
    - shared/engineering.md
    - shared/fsm-verification.md
  trigger:
    "on": [opened, synchronize]
    labels: []

devin:
  enabled: true
  prompts:
    - shared/engineering.md
    - shared/fsm-verification.md
  trigger:
    "on": [opened, synchronize, reopened]
    labels: []

