name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Format check
        run: uvx ruff format --check src/ tests/
      
      - name: Lint
        run: uvx ruff check src/ tests/
      
      - name: Sync dependencies
        run: uv sync
      
      - name: Run tests
        run: uv run pytest tests/ -v

